### ISSUE TITLE
DEB package link is broken

### ISSUE THREAD

**Issue by hcavalle** [sbt/sbt-launcher-package#102]
When trying to download the deb or tar package link for version 0.12.4 links are broken. Eg.  http://scalasbt.artifactoryonline.com/scalasbt/sbt-native-packages/org/scala-sbt/sbt/0.12.4/sbt.tgz

**Comment by eed3si9n** [comment]
Where did you see this link? The official link on the doc is:
http://repo.scala-sbt.org/scalasbt/sbt-native-packages/org/scala-sbt/sbt/0.12.4/sbt.tgz
