### ISSUE TITLE
recommend a JDK, or remove that codepath

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-launcher-package#115]
initially proposed in https://github.com/sbt/sbt-launcher-package/pull/113 there is a check for java version which is insufficient (it doesn't check that the java version is suitable for the version of scala) and suggests a broken remedy: i.e. download a JRE.

Either link to a JDK or don't bother with the check (which is the Windows behaviour).

**Comment by javabrett** [comment]
Probably feedback required here - is there value in running `sbt` with just a JRE and not a JDK - is that valid?

**Comment by fommil** [comment]
@javabrett sbt assumes that `javac` is available.
