### ISSUE TITLE
Installing sbt on Ubuntu pulls in oracle-java9-installer

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-launcher-package#121]
https://twitter.com/omidbbb/status/777912162593288193

```
root@TEA-PC:~# sudo apt-get install sbt
 ...
The following extra packages will be installed:
  oracle-java9-installer
```

**Comment by omidb** [comment]
Using Bash on Ubuntu on Windows (https://github.com/Microsoft/BashOnWindows)
Ubuntu 14.04
following http://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Linux.html

**Comment by eed3si9n** [comment]
> Using Bash on Ubuntu on Windows

oh. ok, so that might be doing something weird.

**Comment by omidb** [comment]
Yeah, that's in Beta but most things working there! Would be great to add documentation to how run it there because it's something people start to use on Windows.
