### ISSUE TITLE
Can debian:publish

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt-launcher-package#125]
Since the upgrade of sbt-native-packager: #110

Complains about the lack of a debian changelog, ie. http://stackoverflow.com/questions/38393297/how-to-solve-changelog-error-for-building-deb-with-sbt-native-packager

Once you give it a changelog it complains "dpkg-genchanges: error: source package has two conflicting values - sbt-launcher-packaging and sbt"

**Comment by eed3si9n** [comment]
Fixed by https://github.com/sbt/sbt-native-packager/pull/961
