### ISSUE TITLE
& in PATH leads to accidental invocation

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-launcher-package#128]
## steps

1. `PATH` contains &
2. run sbt on Windows

## problem

accidental invocation of "MySQL".

## notes

```
PATH=%JAVA_HOME%\bin;%PATH%
```

is not quoted in https://github.com/sbt/sbt-launcher-package/pull/111. /ht @dwijnand

**Comment by dwijnand** [comment]
From http://ss64.com/nt/set.html to solution seems to be:

```bat
-IF DEFINED JAVA_HOME SET PATH=%JAVA_HOME%\bin;%PATH%
+IF DEFINED JAVA_HOME SET "PATH=%JAVA_HOME%\bin;%PATH%"
```

**Comment by fommil** [comment]
+1
