### ISSUE TITLE
/usr/bin/chfn (Permission denied) and OOM after fresh install from 0.13.13.1-1  rpm

### ISSUE THREAD

**Issue by vasigorc** [sbt/sbt-launcher-package#140]
OS: Fedora 25

Hi, I followed the installation steps [from here](http://www.scala-sbt.org/1.0/docs/Installing-sbt-on-Linux.html) for Fedora OS.

My first concern was that it started downloading open-jdk even though I had it on my computer already:

```
Total download size: 12 M
Installed size: 43 M
Is this ok [y/N]: y
Downloading Packages:
(1/5): java-1.8.0-openjdk-1.8.0.121-1.b14.fc25.x86_64.rpm 236 kB/s | 230 kB 00:00
(2/5): sbt-0.13.13.1.rpm 391 kB/s | 1.0 MB 00:02
(3/5): xorg-x11-fonts-Type1-7.5-16.fc24.noarch.rpm 190 kB/s | 522 kB 00:02
(4/5): ttmkfdir-3.0.9-48.fc24.x86_64.rpm 42 kB/s | 56 kB 00:01
(5/5): java-1.8.0-openjdk-devel-1.8.0.121-1.b14.fc25.x86_64.rpm 910 kB/s | 9.8 MB 00:11
```

After running `sbt console` it started downloading all the jars and in the end it crashed:

```
...
downloading https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.4/jansi-1.4.jar ... [SUCCESSFUL ] org.fusesource.jansi#jansi;1.4!jansi.jar (214ms)
:: retrieving :: org.scala-sbt#boot-scala
confs: [default]
5 artifacts copied, 0 already retrieved (24494kB/42ms)
sbt appears to be exiting abnormally.
The log file for this session is at /tmp/sbt8163328394080894174.log java.lang.OutOfMemoryError: GC overhead limit exceeded
```

I tried running this `export SBT_OPTS="-Xms512M -Xmx1536M -Xss2M"` and then do just `sbt`, but it yielded the same result.

This is the full stack trace:

```
sbt appears to be exiting abnormally.
The log file for this session is at /tmp/sbt6601726951581599388.log
java.lang.OutOfMemoryError: GC overhead limit exceeded
at sbt.FilterFiles$$anonfun$handleFile$1.apply(Path.scala:204)
at sbt.FilterFiles$$anonfun$handleFile$1.apply(Path.scala:203)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
at sbt.FilterFiles.handleFile(Path.scala:203)
at sbt.DescendantOrSelfPathFinder.sbt$DescendantOrSelfPathFinder$$handleFileDescendant(Path.scala:215)
at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:217)
at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:216)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
at sbt.DescendantOrSelfPathFinder.sbt$DescendantOrSelfPathFinder$$handleFileDescendant(Path.scala:216)
at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:217)
at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:216)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
at sbt.DescendantOrSelfPathFinder.sbt$DescendantOrSelfPathFinder$$handleFileDescendant(Path.scala:216)
at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:217)
at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:216)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
at sbt.DescendantOrSelfPathFinder.sbt$DescendantOrSelfPathFinder$$handleFileDescendant(Path.scala:216)
at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:217)
at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:216)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
at sbt.DescendantOrSelfPathFinder.sbt$DescendantOrSelfPathFinder$$handleFileDescendant(Path.scala:216)
at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:217)
at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:216)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
at sbt.DescendantOrSelfPathFinder.sbt$DescendantOrSelfPathFinder$$handleFileDescendant(Path.scala:216)
at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:217)
Error during sbt execution: java.lang.OutOfMemoryError: Java heap space
```

**Comment by eed3si9n** [comment]
Could you run `sbt -v` to see the verbose output?

**Comment by vasigorc** [comment]
You may see it below. Does the 'Permission denied' mean that I have to run it under sudo only?

`[process_args] java_version = '1.8.0_121'`
`# Executing command line:`
`java`
`-Xms512M`
`-Xmx1536M`
`-Xss2M`
`-jar`
`/usr/share/sbt/bin/sbt-launch.jar`

`java.io.FileNotFoundException: /usr/bin/chfn (Permission denied)`
`        at java.io.FileInputStream.open0(Native Method)`
`        at java.io.FileInputStream.open(FileInputStream.java:195)`
`        at java.io.FileInputStream.<init>(FileInputStream.java:138)`
`        at sbt.Using$$anonfun$fileInputChannel$1.apply(Using.scala:76)`
`        at sbt.Using$$anonfun$fileInputChannel$1.apply(Using.scala:76)`
`        at sbt.Using$$anon$2.openImpl(Using.scala:65)`
`        at sbt.OpenFile$class.open(Using.scala:43)`
`        at sbt.Using$$anon$2.open(Using.scala:64)`
`        at sbt.Using$$anon$2.open(Using.scala:64)`
`        at sbt.Using.apply(Using.scala:23)`
`        at sbt.IO$.copyFile(IO.scala:638)`
`        at sbt.IO$.sbt$IO$$copyImpl(IO.scala:612)`
`        at sbt.IO$$anonfun$copy$1.apply(IO.scala:603)`
`        at sbt.IO$$anonfun$copy$1.apply(IO.scala:603)`
`        at scala.Function$$anonfun$tupled$1.apply(Function.scala:77)`
`        at scala.Function$$anonfun$tupled$1.apply(Function.scala:76)`
`        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)`
`        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)`
`        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)`
`        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)`
`        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)`
`        at scala.collection.AbstractTraversable.map(Traversable.scala:105)`
`        at sbt.IO$.copy(IO.scala:603)`
`        at sbt.IO$.copyDirectory(IO.scala:627)`
`        at ``sbt.Resolvers$$anonfun$1$$anonfun$apply$9$$anonfun$apply$1.apply$mcV$sp(Resolvers.scala:22)
        at sbt.Resolvers$.creates(Resolvers.scala:141)`
`        at sbt.Resolvers$$anonfun$1$$anonfun$apply$9.apply(Resolvers.scala:22)`
`        at sbt.Resolvers$$anonfun$1$$anonfun$apply$9.apply(Resolvers.scala:22)`
`        at ``sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$3.apply(BuildLoader.scala:88)`
`        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$3.apply(BuildLoader.scala:87)`
`        at scala.Option.map(Option.scala:145)`
`        at sbt.BuildLoader$$anonfun$componentLoader$1.apply(BuildLoader.scala:87)`
`        at sbt.BuildLoader$$anonfun$componentLoader$1.apply(BuildLoader.scala:83)`
`        at sbt.MultiHandler.apply(BuildLoader.scala:15)`
`        at sbt.BuildLoader.apply(BuildLoader.scala:139)`
`        at sbt.Load$.loadAll(Load.scala:365)`
`        at sbt.Load$.loadURI(Load.scala:320)`
`        at sbt.Load$.load(Load.scala:316)`
`        at sbt.Load$.load(Load.scala:305)`
`        at sbt.Load$$anonfun$4.apply(Load.scala:146)`
`        at sbt.Load$$anonfun$4.apply(Load.scala:146)`
`        at sbt.Load$.timed(Load.scala:1025)`
`        at sbt.Load$.apply(Load.scala:146)`
`        at sbt.Load$.defaultLoad(Load.scala:39)`
`        at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:496)`
`        at sbt.BuiltinCommands$.doLoadProject(Main.scala:496)`
`        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)`
`        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)`
`        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)`
`        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)`
`        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)`
`        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)`
`        at sbt.Command$.process(Command.scala:93)`
`        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)`
`        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)`
`        at sbt.State$$anon$1.process(State.scala:184)`
`        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)`
`        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)`
`        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)`
`        at sbt.MainLoop$.next(MainLoop.scala:96)`
`        at sbt.MainLoop$.run(MainLoop.scala:89)`
`        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)`
`        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)`
`        at sbt.Using.apply(Using.scala:24)`
`        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)`
`        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)`
`        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)`
`        at sbt.MainLoop$.runLogged(MainLoop.scala:22)`
`        at sbt.StandardMain$.runManaged(Main.scala:57)`
`        at sbt.xMain.run(Main.scala:29)`
`        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)`
`        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)`
`        at xsbt.boot.Launch$.run(Launch.scala:109)`
`        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)`
`        at xsbt.boot.Launch$.launch(Launch.scala:117)`
`        at xsbt.boot.Launch$.apply(Launch.scala:18)`
`        at xsbt.boot.Boot$.runImpl(Boot.scala:41)`
`        at xsbt.boot.Boot$.main(Boot.scala:17)`
`        at xsbt.boot.Boot.main(Boot.scala)`
`[error] java.io.FileNotFoundException: /usr/bin/chfn (Permission denied)`
`[error] Use 'last' for the full log.`
`project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?`

**Comment by eed3si9n** [comment]
btw you can use enclose multiple lines with triple backtick (```) to format as code.

    ```
    foo
    bar
    ```

**Comment by eed3si9n** [comment]
I have no idea what "/usr/bin/chfn (Permission denied)" is about. Maybe something OpenJDK is doing on Linux?

**Comment by vasigorc** [comment]
It is not only that. Doing chmod 777 on this brings me down to the same issue with /usr/bin/{chsh,sudoreplay,sudoedit} etc.

Btw running this under sudo seems to work.

**Comment by eed3si9n** [comment]
sbt does try to write to several directories such as `~/.sbt` and `~/.ivy2/`. maybe your Fedora is expecting something like XDG Base Directory compliance?

**Comment by vasigorc** [comment]
That is possible. I do have a `$HOME/.config` directory...But I am not sure, variables `$XDG_DATA_HOME, $XDG_CONFIG_HOME` are not set (or empty). How can we confirm that this is causing the issue?

**Comment by cunei** [comment]
I cannot reproduce, under a fresh install of Fedora 25 server: sbt seems to start and operate normally.
There are a couple of considerations. The first is that permissions are affected by SELinux; if you try "ls -lZ" on one of those files, it will also display the relevant SELinux ACL information: it may be that something on your system is set up in an unusual way concerning that aspect. Here I see:
```
$ ls -lZ /usr/bin/chfn
-rws--x--x. 1 root root system_u:object_r:chfn_exec_t:s0 28016 Sep  8 16:28 /usr/bin/chfn
```
You could try `sudo yum reinstall util-linux-user sudo` in order to reinstall the packages and restore the files to their standard privileges.
The second consideration is that sbt should not look at `chfn`, `sudoreplay`, etc. at all. Somehow, it may be that sbt is just looking at the wrong directory when copying files. In that case the error message could just be due to the fact that access privileges prevent the files from being read:
```
$ cp /usr/bin/chfn ~
cp: cannot open '/usr/bin/chfn' for reading: Permission denied
```
When you are starting sbt, does your current directory contain characters like whitespaces or special Unicode characters, by any chance? That might possibly affect the sbt start script.

**Comment by vasigorc** [comment]
Hello,

Thank you for the follow-up. 

I have just tested again and the problem is gone. I have no explanation on why, but I think that at this point we can resolve this issue:
```
[vgorcinschi@myusername ~]$ sbt console
[info] Set current project to vgorcinschi (in build file:/home/vgorcinschi/)
[info] Updating {file:/home/vgorcinschi/}vgorcinschi...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
[info]   Compilation completed in 10.167 s
[info] Starting scala interpreter...
[info] 
Welcome to Scala version 2.10.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions to have them evaluated.
Type :help for more information.

scala> 1+1
res0: Int = 2
```
Anyhow I tried what you suggested in case this will help (without installing anything).

This is the output for the ls -lZ:
```
ls -lZ /usr/bin/chfn 
-rwxrwxrwx. 1 root root system_u:object_r:chfn_exec_t:s0 28016 Sep  8 10:28 /usr/bin/chfn
```

> When you are starting sbt, does your current directory contain characters like whitespaces or special Unicode characters, by any chance?

No -  it is `/home/vgorcinschi`

Thank you.
