### ISSUE TITLE
Replace realpath with something Mac compatible

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-launcher-package#149]
https://github.com/Homebrew/homebrew-core/pull/12264/files#r110583965

Current bash script calls realpath, which doesn't exist on Mac.
The homebrew version gets around this by replacing it with the absolute path, but we probably should implement something that's cross platform like this:

```sh
SCRIPT=$0

# SCRIPT may be an arbitrarily deep series of symlinks. Loop until we have the concrete path.
while [ -h "$SCRIPT" ] ; do
  ls=$(ls -ld "$SCRIPT")
  # Drop everything prior to ->
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    SCRIPT="$link"
  else
    SCRIPT=$(dirname "$SCRIPT")/"$link"
  fi
done

DIR=$(dirname "${SCRIPT}")/..
```

**Comment by dcsobral** [comment]
This doesn't make sense to me. `realpath` was *not* `realpath(1)`, but `realpath()`, a function declared on the `sbt` script *before* sourcing `sbt-launch-lib.bash`. I wonder if the issue wasn't on the brew package side, if they weren't replacing the `sbt` script with their own.

**Comment by eed3si9n** [comment]
It's entirely possible that I got confused by this comment https://github.com/Homebrew/homebrew-core/pull/12264#discussion_r110583965

> Note that realpath won't work on macOS regardless of Homebrew since it's not even a command in the BSD userland, only a C function
