### ISSUE TITLE
"403 Forbidden" when downloading sbt rpm repo files or sbt files 

### ISSUE THREAD

**Issue by Abd4llA** [sbt/sbt-launcher-package#157]
Trying to install sbt either via the rpm repo (I'm on Fedora 25) or just the plain tgz binaries as mentioned in the documentation http://www.scala-sbt.org/release/docs/Installing-sbt-on-Linux.html fails. 

After some debugging it turns out dnf can't download the repomd.xml and receives a 403 response. Then it turns out that I can't actually download any files from https://dl.bintray.com/sbt/rpm or https://dl.bintray.com/sbt/native-packages/sbt/ . They all return 403.

**Comment by Abd4llA** [comment]
Ok it seems it was a temporary issue and it was fixed. Closing it.

**Comment by cmosher01** [comment]
I'm seeing the same thing, as of today:
```sh
$ curl https://bintray.com/sbt/rpm/rpm | tee -a /etc/yum.repos.d/bintray-sbt-rpm.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162    0   162    0     0    518      0 --:--:-- --:--:-- --:--:--   519
#bintray--sbt-rpm - packages by  from Bintray
[bintray--sbt-rpm]
name=bintray--sbt-rpm
baseurl=http://dl.bintray.com/sbt/rpm
gpgcheck=0
repo_gpgcheck=0
enabled=1
$ yum install -y sbt rpm-build
Loaded plugins: fastestmirror, ovl
http://dl.bintray.com/sbt/rpm/repodata/repomd.xml: [Errno 14] HTTP Error 403 - Forbidden
```

**Comment by dwijnand** [comment]
This is duplicate of https://github.com/sbt/sbt/issues/3108.
