### ISSUE TITLE
SBT 0.13.15 tgz has bad signature

### ISSUE THREAD

**Issue by graingert** [sbt/sbt-launcher-package#161]
```sh
$ wget https://dl.bintray.com/sbt/native-packages/sbt/0.13.15/sbt-0.13.15.tgz.asc
$ wget https://dl.bintray.com/sbt/native-packages/sbt/0.13.15/sbt-0.13.15.tgz
$ gpg2 --batch --verify sbt-0.13.15.tgz.asc sbt-0.13.15.tgz
gpg: Signature made Sun 09 Apr 2017 21:25:33 BST
gpg:                using RSA key 99E82A75642AC823
gpg: BAD signature from "sbt build tool <scalasbt@gmail.com>" [unknown]
```

**Comment by eed3si9n** [comment]
Not sure what happened with Bintray. Verified shasum:

```
$ shasum -a 256 sbt-0.13.15.tgz
b6e073d7c201741dcca92cfdd1dd3cd76c42a47dc9d8c8ead8df7117deed7aef  sbt-0.13.15.tgz
```

and re-signed the artifacts.

**Comment by graingert** [comment]
@eed3si9n which one is the correct hash?

You should spend some time on working out how you signed an invalid binary. And announce an analysis of how this breach occurred. 

Did something replace the binary or signature after you released them? Did something trick you into signing the wrong binary?

**Comment by adamchainz** [comment]
😱

**Comment by graingert** [comment]
@eed3si9n bintray automatic signing should NOT be used for infrastructure critical components like SBT.
