### ISSUE TITLE
sbt doesn't start when _JAVA_OPTIONS is set

### ISSUE THREAD

**Issue by liskin** [sbt/sbt-launcher-package#168]
```
[tomi@notes ~]$ export _JAVA_OPTIONS="-Dxxx"
[tomi@notes ~]$ sbt

The java installation you have is not up to date
requires at least version 1.6+, you have
version Picked up _JAVA_OPTIONS: -Dxxx

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .
```

Unfortunately it seems there's no way to silence that "Picked up ..." output and there's no way to put "awt.useSystemAAFontSettings=lcd_hrgb" in /etc/java-8-openjdk/whatever.properties either, so I'm stuck with unsetting _JAVA_OPTIONS whenever I launch sbt. :-(

**Comment by mreid-moz** [comment]
This problem should be fixed by [this commit](https://github.com/sbt/sbt-launcher-package/commit/c487e3166e5decfa2463a1155f216de7de217ee9)

**Comment by liskin** [comment]
Yeah, indeed.

**Comment by mreid-moz** [comment]
I filed https://github.com/sbt/sbt/issues/3593 to get this fix into sbt itself.
