### ISSUE TITLE
Debian package messes with /root and stalls

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-launcher-package#176]
https://twitter.com/debilski/status/897391369320312832 says:

>Hmm, why does the debian #sbt package automatically run sbt about after installation? Messes up /root folder and worse: It hangs doing this.

## expectation

1. Don't mess with /root
2. Don't hang

/cc @Debilski

**Comment by Debilski** [comment]
Opened an issue on sbt/sbt already https://github.com/sbt/sbt/issues/3448
