### ISSUE TITLE
bintray sbt debian is no longer signed

### ISSUE THREAD

**Issue by graingert** [sbt/sbt-launcher-package#181]
E: The repository 'https://dl.bintray.com/sbt/debian  Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by graingert** [comment]
eg https://dl.bintray.com/sbt/debian/Release.asc is 404ing

**Comment by graingert** [comment]
@eed3si9n ^

**Comment by hsenot** [comment]
+1

**Comment by eed3si9n** [comment]
I just recalculated Debian metadata. Hopefully it fixes it.

**Comment by prabcs** [comment]
It works !!
Thanks @eed3si9n for promptly fixing it !

**Comment by eed3si9n** [comment]
There's been many reports about Bintray losing our Debian signature:

- https://github.com/sbt/sbt-launcher-package/issues/208
- https://github.com/sbt/sbt-launcher-package/issues/252
- https://github.com/sbt/sbt/issues/3883
- https://github.com/sbt/sbt/issues/4507

According to Bintray:

> direct downloads from S3 can be unstable from AWS side and we believe this causes problems with the metadata calculation and the loss of signature you mentioned.

Apparently, this bug (`support #105433` or JBT-2992) was finally fixed.
