### ISSUE TITLE
New dependency on 'bc' introduced, not defined by rpm

### ISSUE THREAD

**Issue by fxer** [sbt/sbt-launcher-package#192]
Commit 32e8859df629e39958d095b1c932e26d1ed349b0 (and released in v1.0.3) introduced a new dependency in the code on _bc_ which is not installed by default on many systems (at least not my CentOS 7 servers). However it doesn't look like the dependency was then added to the rpm packaging because I woke up to build failures with the error:

`/usr/share/sbt/bin/sbt-launch-lib.bash: line 207: bc: command not found`

installing the _bc_ package manually cleared all the errors

**Comment by dacjames** [comment]
Same issue on debian.

**Comment by dwijnand** [comment]
Debian was done in https://github.com/sbt/sbt-launcher-package/pull/191.

**Comment by brettryan** [comment]
I can confirm this also fixes git-bash/cygwin installations that do not have bc installed.
