### ISSUE TITLE
checkJava "1.6" insufficient for sbt 1.0.2+ pulling scala 2.12.3 requires JDK8+

### ISSUE THREAD

**Issue by javabrett** [sbt/sbt-launcher-package#193]
See https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt-launch-lib.bash#L265 .

sbt 1.0.2 pulls down 2.12.3 which requires JDK 1.8, so `checkJava "1.6"` is insufficient - install prep continues until:

Error during sbt execution: java.lang.UnsupportedClassVersionError: scala/Option : Unsupported major.minor version 52.0

#115 is somewhat related.

**Comment by dwijnand** [comment]
Perhaps the fix is to use the `sbt.version` in build.properties to pick between `checkJava "1.6"` or `checkJava "1.8"`.

**Comment by fommil** [comment]
this is fixed by the looks of it, but why are we even checking the java version? Java 6 was released in 2006, are we still concerned that somebody tries to start sbt with some old Java 3 install?

**Comment by fommil** [comment]
oh sorry, it's not fixed in the sense that you want it to check java 8. I tihnk it shouldn't check at all.
