### ISSUE TITLE
Regression in Java 10 support

### ISSUE THREAD

**Issue by EmergentOrder** [sbt/sbt-launcher-package#214]
It looks like this was working between the introduction of Java 10 support at [this PR](https://github.com/sbt/sbt-launcher-package/pull/182) and [this commit](https://github.com/sbt/sbt-launcher-package/commit/6ad16c2b74db3e10ce6deb08aab358e931bc64bf#diff-edd0ab5838b2fa424d30f94df800e1f9).
The latter commit though, switches the use of `bc` for `expr` but fails to account for the difference between them.
For Java 7, as expected (in Bash):
```
$ expr 1.7 ">=" 1.6
1
$ echo "1.7 >= 1.6" | bc
1
```

However, for Java 10, they behave differently:
```
$ expr 10 ">=" 1.6
0
$ echo "10 >= 1.6" | bc
1
```

**Comment by EmergentOrder** [comment]
As a result, I get:
```
The Java Development Kit (JDK) installation you have is not up to date.
requires at least version 1.6+, you have
version 10

Please go to http://www.oracle.com/technetwork/java/javase/downloads/ and download
a valid JDK and install before running .

```
When I try to run sbt with Java 10

**Comment by smarter** [comment]
I fixed it once, I'm not going to fix it again :p

**Comment by smarter** [comment]
@dwijnand Would it be possible to release new tarballs for sbt 1 and 0.13 at https://www.scala-sbt.org/download.html that use a fixed launcher? Especially for 0.13 we shouldn't wait until a hypothetical 0.13.18 is released to fix this.

**Comment by dwijnand** [comment]
I'll see how @eed3si9n feels about yet another sbt 0.13 release.

**Comment by EmergentOrder** [comment]
thanks @2m @dwijnand
