### ISSUE TITLE
Consider dropping `checkJava "6"`

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt-launcher-package#224]
as @fommil [mentions](https://github.com/sbt/sbt-launcher-package/commit/5a0bde442dec7d9a1bdc35655541902fb873172a#r28226465):

> why are we even still checking this... Java 6 was released in 2006

perhaps we should just lose it.

or (#193) make it check for Java 8 iff sbt.version >= sbt 1..

**Comment by fommil** [comment]
to expand on my reasoning... I don't see any value in checking for the version of java.

The Java versioning numbers are in flux and will probably continue changing with every release, making this check have more false negatives that true positives.

In addition, if the wrong version of java is used, java will complain about bytecode versions using an easily googled error message that any developer will be able to understand.

Finally, it's ethically wrong for free software to recommend the use of proprietary software. A download link should be to OpenJDK, not the Oracle proprietary binaries.

**Comment by eed3si9n** [comment]
We use the detected JDK version to move rt.jar so we can run sbt on JDK 9 onwards.

**Comment by eed3si9n** [comment]
Maybe but either case we need to know about Java version in bash/batch.
