### ISSUE TITLE
Unable to run sbt

### ISSUE THREAD

**Issue by NofelYaseen** [sbt/sbt-launcher-package#233]
I installed sbt using

	echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
	sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
	sudo apt-get update
	sudo apt-get install sbt

Now when I run

	sudo sbt package

I get the error:

	Getting org.scala-sbt sbt 1.1.6  (this may take some time)...
	Warning: default mime table not found: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/content-types.properties

	:: problems summary ::
	:::: WARNINGS
			module not found: org.scala-sbt#sbt;1.1.6

		==== local: tried

		  /root/.ivy2/local/org.scala-sbt/sbt/1.1.6/ivys/ivy.xml

		  -- artifact org.scala-sbt#sbt;1.1.6!sbt.jar:

		  /root/.ivy2/local/org.scala-sbt/sbt/1.1.6/jars/sbt.jar

		==== local-preloaded-ivy: tried

		  file:////root/.sbt/preloaded/org.scala-sbt/sbt/1.1.6/ivys/ivy.xml

		==== local-preloaded: tried

		  file:////root/.sbt/preloaded/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.pom

		  -- artifact org.scala-sbt#sbt;1.1.6!sbt.jar:

		  file:////root/.sbt/preloaded/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.jar

		==== Maven Central: tried

		  https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.pom

		  -- artifact org.scala-sbt#sbt;1.1.6!sbt.jar:

		  https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.jar

		==== sbt-maven-releases: tried

		  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.pom

		  -- artifact org.scala-sbt#sbt;1.1.6!sbt.jar:

		  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.jar

		==== sbt-maven-snapshots: tried

		  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.pom

		  -- artifact org.scala-sbt#sbt;1.1.6!sbt.jar:

		  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.jar

		==== typesafe-ivy-releases: tried

		  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/1.1.6/ivys/ivy.xml

		==== sbt-ivy-snapshots: tried

		  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/1.1.6/ivys/ivy.xml

			::::::::::::::::::::::::::::::::::::::::::::::

			::          UNRESOLVED DEPENDENCIES         ::

			::::::::::::::::::::::::::::::::::::::::::::::

			:: org.scala-sbt#sbt;1.1.6: not found

			::::::::::::::::::::::::::::::::::::::::::::::

	:::: ERRORS
		Server access Error: sun.security.validator.ValidatorException: No trusted certificate found url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.pom

		Server access Error: sun.security.validator.ValidatorException: No trusted certificate found url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.jar

		Server access Error: sun.security.validator.ValidatorException: No trusted certificate found url=https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.pom

		Server access Error: sun.security.validator.ValidatorException: No trusted certificate found url=https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.jar

		Server access Error: sun.security.validator.ValidatorException: No trusted certificate found url=https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.pom

		Server access Error: sun.security.validator.ValidatorException: No trusted certificate found url=https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.jar

		Server access Error: sun.security.validator.ValidatorException: No trusted certificate found url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/1.1.6/ivys/ivy.xml

		Server access Error: sun.security.validator.ValidatorException: No trusted certificate found url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/1.1.6/ivys/ivy.xml

	:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
	unresolved dependency: org.scala-sbt#sbt;1.1.6: not found
	Error during sbt execution: Error retrieving required libraries
	  (see /root/.sbt/boot/update.log for complete log)
	Error: Could not retrieve sbt 1.1.6

I am using openjdk version "1.8.0_171" and I am able to access the urls using wget.

**Comment by eed3si9n** [comment]
There's been lots SSL related issues due to https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1739631.
I am not sure if your problem is related.

**Comment by NofelYaseen** [comment]
I managed to solved the issue using:

    sudo dpkg --purge --force-depends ca-certificates-java
    sudo apt-get install ca-certificates-java

and removing /home/username/.sbt/repositories
