### ISSUE TITLE
Error: Unknown repo: 'bintray--sbt-rpm' on Fedora 28

### ISSUE THREAD

**Issue by PTrottier** [sbt/sbt-launcher-package#234]
When running `sudo dnf --enablerepo=bintray--sbt-rpm install sbt` in the Terminal of Fedora 28, it throws the following error: 
> Error: Unknown repo: 'bintray--sbt-rpm'

From the Fedora instructions here: https://www.scala-sbt.org/release/docs/Installing-sbt-on-Linux.html

**Comment by eed3si9n** [comment]
@PTrottier Did you run

```
curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo
```

?

**Comment by PTrottier** [comment]
@eed3si9n Running the above rectified the issue. Thank you for your time!
