### ISSUE TITLE
sbt 1.2.7 fails to sync preloaded libraries

### ISSUE THREAD

**Issue by m-yamaguchi** [sbt/sbt-launcher-package#246]
In syncPreloaded() of sbt-launch-lib.bash (Line 263),
the following rsync command is missing a trailing slash of the source directory ("$source_preloaded").

  `rsync -a --ignore-existing "$source_preloaded" "$target_preloaded"`

So, local-preloaded files are copied to $target_preloaded/local-preloaded/

The following command will work as expected.

  `rsync -a --ignore-existing "$source_preloaded/" "$target_preloaded"`

**Comment by eed3si9n** [comment]
Thanks for the report.
