### ISSUE TITLE
Preloaded Ivy repository is missing scala-compiler

### ISSUE THREAD

**Issue by larsrh** [sbt/sbt-launcher-package#250]
Compare this failing build:

https://ci.appveyor.com/project/larsrh/sbt-libisabelle/builds/21416903

with this (old) succeeding one:

https://ci.appveyor.com/project/larsrh/sbt-libisabelle/builds/19871377

The new build apparently lacks some Scala dependencies in the preloaded Ivy repository. This affects sbt 1.2.7.

**Comment by eed3si9n** [comment]
I just ran into this myself. It seems like preloaded has 2.12.6 ivy files, but not jar files.
I am not sure what's causing this behavior.
