### ISSUE TITLE
On Linux, SBT_OPTS cannot specify -no-colors

### ISSUE THREAD

**Issue by MichaelJAllen** [sbt/sbt-launcher-package#260]
- [X] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
I'm running _SBT_ 1.1.6 on Linux Mint 18.3.

To reproduce, try this in a bash terminal:
```
export SBT_OPTS="-no-colors -batch"
sbt test
```

## problem
Output of prior commands is as follows:
```
Unrecognized option: -no-colors
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

## expectation

_SBT_ should have run successfully in non-interactive mode without any errors.

## notes

sbt version: *1.1.6*

Oddly, this works:
```
export SBT_OPTS="-Dsbt.log.noformat=true"
sbt test
```

It looks as though `SBT_OPTS` is not being parsed correctly: _SBT_ options are ignored, but JVM-style options are accepted.

**Comment by eed3si9n** [comment]
I've created two issues #261 and #262 to track what seems to be different issue from the whole -no-colors thing.
