### ISSUE TITLE
On Linux, -Xss6M cannot be specified from SBT_OPTS

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-launcher-package#262]
Have same problem with sbt 1.2.7.

The problem is that the options are appended after any command line args, e.g.:
```
[residual] arg = 'test'
Using sbt options defined in variable $SBT_OPTS
[residual] arg = '-Xss2m'
[residual] arg = '-XX:MaxMetaspaceSize=768m'
Detected sbt version 1.2.7
Using jvm options defined in file /etc/sbt/jvmopts
# Executing command line:
java
-Xms2048M
-Xmx2048M
-Xss6M
-XX:MaxPermSize=512M
-jar
/home/travis/.sbt/launchers/1.2.7/sbt-launch.jar
test
-Xss2m
-XX:MaxMetaspaceSize=768m
```
The last two lines should appear before `-jar` and certainly not _after_ `test`.  Behavior on MacOS is correct:
```
[process_args] java_version = '8'
# Executing command line:
java
-Xss2m
-XX:MaxMetaspaceSize=768m
-jar
/usr/local/Cellar/sbt/1.2.7/libexec/bin/sbt-launch.jar
test
```
On Linux, the `sbt` script synthesized the final invocation command as 
```
  execRunner "$java_cmd" \
    "${extra_jvm_opts[@]}" \
    "${java_args[@]}" \
    -jar "$sbt_jar" \
    "${sbt_commands[@]}" \
    "${residual_args[@]}"
```
and on MacOS as
```
execRunner "$java_cmd" \
    $(get_mem_opts $sbt_mem) \
    $(get_gc_opts) \
    ${JAVA_OPTS} \
    ${SBT_OPTS:-$default_sbt_opts} \
    ${java_args[@]} \
    -jar "$sbt_jar" \
    "${sbt_commands[@]}" \
    "${residual_args[@]}"
```
Writing scripts that work in both environments is next to impossible.

_Originally posted by @jeffrey-aguilera in https://github.com/sbt/sbt-launcher-package/issues/260#issuecomment-450007476_

**Comment by eed3si9n** [comment]
macOS and Linux should have the same behavior since they come from the same files. There are some slight modification Home Brew adds, but I don't think it should affect this.

**Comment by eed3si9n** [comment]
@jeffrey-aguilera From the looks of your snippet you quoted for Linux, it seems like it's using sbt-extras. If so try using `-J-X` as @outkaj noted, or install the Lightbend sbt script available from apt-get.

**Comment by jeffrey-aguilera** [comment]
`sbt-extras` is installed by Travis-CI, apparently: https://docs.travis-ci.com/user/languages/scala/
