### ISSUE TITLE
Should the realpath function have been removed?

### ISSUE THREAD

**Issue by dcsobral** [sbt/sbt-launcher-package#269]
The sbt script had this thing in it:
```bash
realpath () {
(
  TARGET_FILE="$1"
  FIX_CYGPATH="$2"

  cd "$(dirname "$TARGET_FILE")"
  TARGET_FILE=$(basename "$TARGET_FILE")

  COUNT=0
  while [ -L "$TARGET_FILE" -a $COUNT -lt 100 ]
  do
      TARGET_FILE=$(readlink "$TARGET_FILE")
      cd "$(dirname "$TARGET_FILE")"
      TARGET_FILE=$(basename "$TARGET_FILE")
      COUNT=$(($COUNT + 1))
  done

  # make sure we grab the actual windows path, instead of cygwin's path.
  if [[ "x$FIX_CYGPATH" != "x" ]]; then
    echo "$(cygwinpath "$(pwd -P)/$TARGET_FILE")"
  else
    echo "$(pwd -P)/$TARGET_FILE"
  fi
)
}
```
The sbt-launch-lib.bash script had this:
```bash
declare SCRIPT=$0
while [ -h "$SCRIPT" ] ; do
  ls=$(ls -ld "$SCRIPT")
  # Drop everything prior to ->
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    SCRIPT="$link"
  else
    SCRIPT=$(dirname "$SCRIPT")/"$link"
  fi
done
```
When they got merged, the former was dropped for the latter. 

I think that's a mistake. Relying on text manipulation instead of using something specifically designed to retrieve link destinations by shell scripts seems fraught with issues. Consider, for example, the possibility of the path containing `->`. I'll grant that `ls(1)` is specified by POSIX, and `readlink(1)` is not, but it is widespread and I don't see any issues related to it not working.

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-launcher-package/pull/270
