### ISSUE TITLE
Problems with Customized Installation Path on Windows

### ISSUE THREAD

**Issue by dcsobral** [sbt/sbt-launcher-package#28]
The installation path on Windows does not seem to work at all. It always installs on my 32 bit application path even though I try to override it with the 64 bit application path.

One other thing I noticed is that the path installation option disappears if I de-select the PATH update "component". I haven't tried other components, and this is not related to the first problem (I tried these things on different installs).

**Comment by dwijnand** [comment]
Fixed in https://github.com/sbt/sbt-launcher-package/pull/110
