### ISSUE TITLE
Bintray soon to be sunsetted

### ISSUE THREAD

**Issue by nicholasnbg** [sbt/sbt-launcher-package#348]
As per https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ Bintray will be sunsetted as of May 1, 2021.

We are currently looking to update/remove any dependencies that rely on bintray,  and a number of systems follow these instructions for pulling down and installing sbt: https://www.scala-sbt.org/release/docs/Installing-sbt-on-Linux.html

Just checking in to see if there are any plans to publish someplace else

**Comment by eed3si9n** [comment]
@nicholasnbg I have an issue here to track Bintray sunset - https://github.com/sbt/sbt/issues/6294
Feel free to comment there.
