### ISSUE TITLE
SBT can't be uninstalled/upgraded on Windows

### ISSUE THREAD

**Issue by alexeyr** [sbt/sbt-launcher-package#38]
I've installed SBT 0.12 with MSI installer. When trying to install SBT 0.12.1 I get the message 

> Another version of this product is already installed.  Installation of this version cannot continue.  To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel.

However, SBT doesn't appear in the Programs part of the Control Panel so I can't remove it.

**Comment by sumkincpp** [comment]
+1

**Comment by seanf** [comment]
+1 Caught me out.  I tried searching for "sbt" and "scala", but not "simple".

**Comment by xhudik** [comment]
+1

**Comment by lsolano** [comment]
Found as "Simple Build Tool" just as @csatadiadam said. 

I was going from `0.13.5.x` to `0.13.9.2`

**Comment by zcsongor** [comment]
+1

**Comment by eed3si9n** [comment]
This should be fixed now.
