### ISSUE TITLE
"Ham fisted" memory settings keep sbt from launching on machines with less than 1GB of memory unnecessarily 

### ISSUE THREAD

**Issue by williscool** [sbt/sbt-launcher-package#57]
https://github.com/sbt/sbt-launcher-package/blob/full-packaging/src/universal/bin/sbt-launch-lib.bash#L80h

``` bash
# a ham-fisted attempt to move some memory settings in concert
# so they need not be dorked around with individually.
get_mem_opts () {
  local mem=${1:-1024}
  local perm=$(( $mem / 4 ))
  (( $perm > 256 )) || perm=256
  (( $perm < 1024 )) || perm=1024
  local codecache=$(( $perm / 2 ))

  echo "-Xms${mem}m -Xmx${mem}m -XX:MaxPermSize=${perm}m -XX:ReservedCodeCacheSize=${codecache}m"
}
```

Sbt wont launch on my digital ocean (512 M)  Ubuntu droplet without me commenting the echo in this function out because it overrides my env settings.

**Comment by fommil** [comment]
`JAVA_OPTS` is used, I think this can be closed. `.jvmopts` support coming real soon.
