### ISSUE TITLE
JDK8 compat issue, MaxPermSize removed since JDK 8

### ISSUE THREAD

**Issue by netroby** [sbt/sbt-launcher-package#67]
JDK8 compat issue, MaxPermSize removed since JDK 8

See https://github.com/sbt/sbt/pull/1359

**Comment by jsuereth** [comment]
These should all now be available in sbt 0.13.7, and soon to be release sbt 0.13.8

**Comment by netroby** [comment]
After more than half years , you fixed it. thanks.

**Comment by seanf** [comment]
This warning still appears when running sbt 0.13.8 (MSI installer) with Java 8 on Windows 8 64-bit.  The file `sbtconfig.txt` just has `-XX:MaxPermSize=256m` with no sign of a version check.
