### ISSUE TITLE
Chrome indicates Windows installer as malware

### ISSUE THREAD

**Issue by sqlrob** [sbt/sbt-launcher-package#68]
Chrome marks the latest SBT installer download as malware. This may be due to a simple name match, since there is a trojan called sbt.

Seen on Chrome 35.0.1916.114m on Windows 7. Also seen on Windows 8.1, but I don't have that system in front of me to check the Chrome version.

I have an earlier version of an sbt msi that isn't version tagged, SHA1 of f3871740ad9118d98391573af674d40220082738. This wasn't indicated as malicious when I downloaded it in April. This is not signed, so this probably isn't #31, as one was OK and one isn't.
![sbt](https://cloud.githubusercontent.com/assets/926539/3154987/bb28ef64-eab6-11e3-8f66-c09279299d54.png)

VirusTotal shows  sbt-0.13.5.msi as clean as of the filing of this issue.

**Comment by jsuereth** [comment]
This is an issue with the configuration hook in [WiX](http://wixtoolset.org/) being detected as malicious.  I'll see if we bump versions and the issue goes away.
