### ISSUE TITLE
RPM spec file not available on Github

### ISSUE THREAD

**Issue by loicdescotte** [sbt/sbt-launcher-package#74]
It would be nice to be able to rebuild the SBT RPM from RPM sources.
I didn't find any spec or srpm file on Github. Is it available somewhere? Or can it be pushed on this github repository? We would be able to do some Pull Requests to improve it.

Thanks

**Comment by jsuereth** [comment]
The SPEC file is autogenerated by the sbt-native-packager plugin.  If you want to modify the RPM spec, you need to modify the sbt build.

I believe someone has added (or is adding) the ability to generate source RPMs in sbt-native-packager, but it's not quite finished yet.
