### ISSUE TITLE
Missing newline at end of sbtopts file causes last line to be silently ignored 

### ISSUE THREAD

**Issue by greenrd** [sbt/sbt-launcher-package#88]
The ubiquitous bashism

```
while read line; do

done
```

is buggy. It ignores the last line of `sbtopts` if the last line does not end with a newline character - and this is actually due to the specified behaviour of the `read` builtin! See e.g. http://stackoverflow.com/questions/4165135/how-to-use-while-read-bash-to-read-the-last-line-in-a-file-if-there-s-no-new

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt-launcher-package/pull/169
