### ISSUE TITLE
sbt in interactive mode hangs in git for windows bash

### ISSUE THREAD

**Issue by TLmaK0** [sbt/sbt-launcher-package#95]
## Steps ##
* Download a windows git version from https://git-scm.com/download/win .
* During install check `Use mintty (the default terminal of MSys2)`.
* Run `git-bash.exe`
* Run `sbt`
* Type `tasks` and press enter

## Problems ##
* Console hangs, and only can exit with Ctrl+C

## Expectations ##
* Console should return sbt tasks

**Comment by naegelejd** [comment]
This fix would be great.

**Comment by leerobertw** [comment]
Another vote to fix it.
